### ISSUE TITLE
Capital P please.

### ISSUE THREAD

**Issue by verioussmith** [anthify/es6-sass-hotreloading-docker-wordpress-theme#8]
A small change but will increase your credibility. As an experienced WordPress developer I can tell you that all true WordPress Devs cringe when they see WordPress spelled with a lower case "p" and not a capital "P".  There is even a function in the documentation written to correct "Wordpress" to "WordPress"

https://codex.wordpress.org/Function_Reference/capital_P_dangit

So... Small change but you will have a big effect.

**Comment by anthify** [comment]
Cringe no more, sir.
